Mobile skeleton
Piercel2022/portfolio-skeleton pull request #2
Opened 2022-05-24 23:40 UTC by Piercel2022

There are two sections for this project:

the toolbar (or header) containing the logo and the hamburger menu
the headline containing the welcome message, the description of portfolio'website and the connection to the social media.

2022-05-25 00:33 UTC, Kakalanp requested changes
# Hello there @Piercel2022! <img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="28px" alt="hi">

### Good job so far! :tada: 

There are some issues that you still need to work on to go to the next project but you are almost there! :pinching_hand: 

<img src="https://media.giphy.com/media/Qaxd5XpgDWMso/giphy.gif" alt="so close">

## Highlights :+1: 
- No linter errors :heavy_check_mark:
- Repo looks professional :briefcase:
- Solid pull request :scroll:
- Excellent use of flexbox :monocle_face: 

## Required Changes ♻️
***Check the comments under the review.***

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 00:33 UTC, Kakalanp commented on index.html
> +            <div class="logo">Pierre</div>
The logo on the top-left of a web page is to facilitate navigation by allowing the user to click it and be back at the start :monocle_face:

Kindly change the `<div>` tag to an `<a>` tag, that way, users can easily navigate your portfolio! :100:

2022-05-25 00:33 UTC, Kakalanp commented on README.md
> +This project is [MIT](./MIT.md) licensed.
[OPTIONAL]

Your MIT license does not exist, you can create one at the start of your project or follow [this guide](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to add it now :clinking_glasses:

2022-05-25 00:33 UTC, Kakalanp commented on index.html
> +            <div class="burger-menu">
It's always a good practice to use semantic tags, when we want to add navigation links, we contain them in a `<nav>` tag, kindly make this small change to make your portfolio more professional :wink:

2022-05-25 00:33 UTC, Kakalanp commented on index.html
> +            <img src="images/header-shapesmobile.svg" alt="background" >
background images should be set as `background-image` in your CSS file, that way we make sure that this `<img>` tag doesn't break anything in the future! :mag:

2022-05-25 00:33 UTC, Kakalanp commented on index.html
> +                <li><a href="#"><img src="images/two-finger.svg" alt="two-fingers" id="two-fingers"></a></li>
Looks like you forgot to add the links to your social media :sweat_smile: 

Remember that the point of having these icons is to give the user an easy way to connect with you, just in case you forgot how to do it: `<a href="https://twitter.com/YOURUSERNAME">` :rocket:

2022-05-25 06:47 UTC, Piercel2022 commented on index.html
> +                <li><a href="#"><img src="images/two-finger.svg" alt="two-fingers" id="two-fingers"></a></li>
Hello @Kakalanp should I remove the icons I didn't have an account know? I have only 3 accounts ( Linkedin, GitHub and then twitter)

2022-05-25 12:29 UTC, aimemalaika approved these changes
Hi @Piercel2022, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 12:29 UTC, aimemalaika commented on index.html
> +            <div class="burger-menu">
👍🏽

2022-05-25 12:29 UTC, aimemalaika commented on README.md
> +This project is [MIT](./MIT.md) licensed.
👍🏽

2022-05-25 12:37 UTC, merged

2022-05-31 07:18 UTC, AsimKhan2019 reviewed
# Good Job

Time to merge your code. 👍